### ISSUE TITLE
feat: TextMate/Sublime Text theme

### ISSUE THREAD

**Issue by mhanberg** [sainnhe/forest-night#29]
In order to use this theme with [`bat`](https://github.com/sharkdp/bat), I have converted the Visual Studio Code version of this theme to a text mate version using the [Code Theme Converter](https://github.com/tobiastimm/code-theme-converter) tool.

I would like to share this theme so other's can use it.

My question is, should I create my own repository to host this theme, or should I PR this repository? 

I mainly ask because the VSCode version of the theme has it's own repository.

Thanks!

**Comment by sainnhe** [comment]
Hi, I want to share some of my views.

This question is actually a discussion about whether it should be centralized or distributed. I think it's better to be distributed, for the following reasons:

1. Easier to maintain. A "monorepo" can make some things more complicated. For example, if we keep all of them in one repository, it means we need to deal with all the issues here. In addition, it's harder to manage tags. I have to put the vscode theme in a separate repository exactly because of this.

2. Longer life cycle. A color scheme is unlike other open source projects, as long as its color palette exists, it can survive forever. Imagine when we no longer participate in maintenance after ten or twenty years, people can still take over a project by forking it and editing the wiki page, without the consent of anyone.

3. More positive feedback for maintainers. Don't you want to create a separate repository so that you can get more stars?

I put some ports in this repository at the very beginning simply because of I'm too lazy to create one more repository. At that time I did not consider long-term maintenance at all, and now I think it's a mistake.

What about let's put all other ports into separate repositories or gists? @mhanberg @jef

**Comment by jef** [comment]
Part of me thinks we should have an org. I know that wasn't your goal in the beginning, but I'm starting to think to have an org that we can use and maintain repos. And pull in ports that become increasingly stable.

That being said, I do agree to an extent that having separate repositories makes sense for the reasons you listed, irregardless of org or others repos.

Great examples of this are Nord and Dracula.

I'd also add combining Forest Night and Gruvbox Material (and others that are similar) is a great use case of doing this too. Having different "flavors" of an overarching color scheme that we can define. I think this is a little more extreme solution, but still something worth mentioning.

**Comment by sainnhe** [comment]
I agree that creating an org is good for maintenance, actually I have created an org for gruvbox-material before, but I deleted it for some reasons.

An org means the official to some extent, which makes a psychological disorder for those who do not want to be constrained(for example, me). I distribute this color scheme under the MIT license to give developers enough freedom. If you want to modify the colors, that's OK. If you want to use your project to make money, that's OK. If you do not want to share your project, that's OK. If you want to share your project, just edit the wiki.

A good example is gruvbox, and I have to say that I love this way. As an OSS developer, I feel free enough.

I think an org should be used to maintain a huge project instead of organizing related projects. A color scheme is a very small project, I think adding collaborators is already enough.

Another reason is very personal, I have designed some other color schemes and I may design more in the future. I want to treat them the same. That's said, I don't what to create an org for one color scheme but do not do so for another. However, creating an org for each color scheme is not a good idea, because some are worth doing so, but some are not. In addition, creating an org for each color scheme is very troublesome and I don't want to join a bunch of orgs that hold a single color scheme.

**Comment by jef** [comment]
> I don't want to join a bunch of orgs that hold a single color scheme.

That's for sure. I don't think anyone wants to maintain that mess.

Okay, so it seems that we should have ports that make sense outside of this repository. Good examples are the ones I've recently posted as well as with what @mhanberg has done.

Is that something we should go ahead and do? I also think making all the colors and their hex codes apparent on the main README would be good, so that others can create their ports with a good starting direction.

**Comment by sainnhe** [comment]
Let's move the ports in this repo to new repos or gists, make this repository only be used to hold the vim color scheme.

I've moved the ports for alacritty and zsh to github gists, and the wiki has been updated.

As for the color codes, I'll create a new gist and add its link in the wiki page.

**Comment by jef** [comment]
> I've moved the ports for alacritty and zsh to github gists, and the wiki has been updated.

That makes sense. I guess since there only really config files. I'll do the same for the ones I made that are only config

> As for the color codes, I'll create a new gist and add its link in the wiki page.

Take a look at the colors section here. This would be kind of cool to do something like this: https://github.com/ayu-theme/ayu-colors#colors

Side note: _I'm still kind of for the idea of an org :laughing:_

**Comment by sainnhe** [comment]
Thanks for your suggestion. I do understand that creating an org might be beneficial for maintenance, but I think giving developers freedom is more important than anything. As long as this color scheme is good enough, there will always be someone who would like to take over this project.

So don't worry about the maintenance, take a look at gruvbox and solarized, they didn't create an org but they still did a very good job.

**Comment by sainnhe** [comment]
@mhanberg Could you create your own repository to host the theme and add a link in the wiki page?

**Comment by jef** [comment]
> So don't worry about the maintenance, take a look at gruvbox and solarized, they didn't create an org but they still did a very good job.

That's true.

**Comment by mhanberg** [comment]
Hi, I have uploaded the textmate theme to this repo: https://github.com/mhanberg/forest-night-textmate.
